# Generated by Django 3.2.8 on 2021-10-26 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('update_date', models.DateTimeField(verbose_name='last update date')),
            ],
        ),
        migrations.CreateModel(
            name='TodoListHasTodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TodoList.todoitem')),
                ('todolist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TodoList.todolist')),
            ],
        ),
    ]
