# Generated by Django 3.2.8 on 2021-10-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolisthastodoitem',
            old_name='todoitem_id',
            new_name='todoitem',
        ),
        migrations.RenameField(
            model_name='todolisthastodoitem',
            old_name='todolist_id',
            new_name='todolist',
        ),
    ]
