# Generated by Django 3.2.8 on 2021-10-26 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0002_auto_20211026_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 9, 20, 18, 226240, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 9, 20, 18, 178620, tzinfo=utc), verbose_name='date published'),
        ),
    ]
