# Generated by Django 3.2.8 on 2021-10-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0004_auto_20211026_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last update date'),
        ),
    ]
