# Generated by Django 3.2.8 on 2021-10-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0005_auto_20211026_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='name',
            field=models.CharField(default='My TodoList', max_length=200),
        ),
    ]
