# Generated by Django 3.2.8 on 2021-10-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0006_todolist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
