# Generated by Django 3.2.8 on 2021-10-26 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0007_alter_todolist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update date'),
        ),
    ]
