# Generated by Django 3.2.8 on 2021-10-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0008_alter_todolist_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last update date'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last update date'),
        ),
    ]
